// Registering the offline cache, and the way back out of it.
//
// A service worker that caches wrongly is one of the few bugs a static site
// cannot fix by deploying again — the broken worker is what decides whether
// the fix is ever fetched. So this file is mostly about the exits:
//
//   ?nosw=1   unregisters every worker on this scope and empties its caches,
//             then reloads clean. The escape hatch, for a browser that has got
//             itself stuck and for anyone testing that it can be got out of.
//   dev       never registers at all. Vite serves unhashed modules, which is
//             precisely the thing the app cache assumes cannot happen.
//
// The worker itself never caches index.html ahead of the network, so a new
// deploy is picked up on the next load either way.

import type { Meta } from "./loader";

/**
 * A stable fingerprint of the city data this build is serving.
 *
 * meta.json is regenerated by `npm run build-data` alongside every binary, and
 * it carries the counts and the extent — so any rebuild that changed the city
 * changes this string, and a rebuild that changed nothing does not. FNV-1a
 * because it needs to be deterministic and cheap, not secure.
 */
export function dataVersion(meta: Meta): string {
  const s = JSON.stringify(meta);
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return `${meta.version}-${(h >>> 0).toString(36)}`;
}

/** Tear the worker down and take its caches with it. Used by `?nosw=1`. */
async function unregisterAll(): Promise<void> {
  const regs = await navigator.serviceWorker.getRegistrations();
  await Promise.all(regs.map((r) => r.unregister()));
  if ("caches" in self) {
    for (const name of await caches.keys()) {
      if (name.startsWith("rtm-")) await caches.delete(name);
    }
  }
}

export async function registerServiceWorker(meta: Meta): Promise<void> {
  if (!("serviceWorker" in navigator)) return;

  if (new URLSearchParams(location.search).has("nosw")) {
    await unregisterAll();
    // strip the flag so a reload does not immediately unregister again
    const url = new URL(location.href);
    url.searchParams.delete("nosw");
    location.replace(url.toString());
    return;
  }

  // Dev serves unhashed module URLs, so an app cache keyed on the filename
  // would pin whatever was open when the worker installed.
  if (!import.meta.env.PROD) return;

  try {
    // Resolved against the document, not against import.meta.url: the worker
    // ships from public/ and is served at the app's base, while this module is
    // bundled into assets/ — so import.meta.url would look for it one
    // directory too deep, and a worker cannot claim a scope above its own path.
    const swUrl = new URL(`${import.meta.env.BASE_URL}sw.js`, location.href);
    await navigator.serviceWorker.register(swUrl.href, {
      scope: new URL("./", location.href).pathname,
    });
    // Tell whichever worker is actually in control which city is on disk. The
    // freshly-registered one may still be installing, so wait for a controller
    // rather than posting into the void.
    const version = dataVersion(meta);
    const tell = () => navigator.serviceWorker.controller?.postMessage({ type: "data-version", version });
    if (navigator.serviceWorker.controller) tell();
    else navigator.serviceWorker.addEventListener("controllerchange", tell, { once: true });
  } catch {
    // A blocked or unsupported worker costs nothing here: every fetch in the
    // app works exactly as it did before, just without the cache.
  }
}
